Feature: PostCSS import
arcticicestudio/nord pull request #88
Opened 2018-01-16 08:16 UTC by marcobiedermann

Add style field to `package.json` and add section to readme.

> When importing a module, it will look for index.css or file referenced in `package.json` in the `style` or `main` fields. You can also provide manually multiples paths where to look at.
[postcss-import](https://github.com/postcss/postcss-import)

2018-01-16 13:12 UTC, arcticicestudio requested changes
Thanks for your contribution :+1: 

Nice addition to simplify the usage/import. I've saw the field in some other projects, but never really investigated time to check which package makes use of this custom field :smile: 

Added some small change requests, but everything else looks fine.

2018-01-16 13:21 UTC, marcobiedermann commented
You are very welcome. Yeah, I did not know of this either a couple of weeks ago.

> Added some small change requests, but everything else looks fine.

Sorry but I can not find any [reviews](https://github.com/arcticicestudio/nord/pull/88#pullrequestreview-89090013)

2018-01-16 14:12 UTC, arcticicestudio commented
Sorry, I've posted the reviews after the first comment, refresh the page to see them.

2018-01-16 19:34 UTC, marcobiedermann commented
I am really sorry but I can not find any pending requests / reviews from you on the PR:
![image](https://user-images.githubusercontent.com/5244986/35008356-71a5d870-fafc-11e7-894f-13f717f28d78.png)
Clicking on "View Changes" lead to https://github.com/arcticicestudio/nord/pull/88/files/604d3dba836178ba4aa90eef1be9a46a19fe4a05 which are the changes I made.
Even if I would, I can not approve my modifications because this can not be done from the same owner.
Either am I overlooking something obvious or have to review and request some changes again

2018-01-16 19:44 UTC, arcticicestudio requested changes

2018-01-16 19:44 UTC, arcticicestudio commented on README.md
> +When using [postcss-import](https://github.com/postcss/postcss-import) you can simply import the CSS file like any JavaScript module:
Please change the *inline* link to the GitHub repository to a *reference* link and place it at the bottom of the document. You can name it `postcss-import-gh` to adapt to the naming style of the other links.

2018-01-16 19:44 UTC, arcticicestudio commented on README.md
> +When using [postcss-import](https://github.com/postcss/postcss-import) you can simply import the CSS file like any JavaScript module:
Can you also please add the new paragraph to the documentation in the *Usage* chapter ([`docs/getting-started/usage.md`][ref])

[ref]: https://github.com/arcticicestudio/nord/blob/develop/docs/getting-started/usage.md

2018-01-16 19:46 UTC, arcticicestudio commented
Alright, I forgot to submit the pending change requests after adding the comments :upside_down_face:

2018-01-16 22:59 UTC, marcobiedermann commented
Haha, I thought for a second I am really overlooking something.
Fixed in https://github.com/arcticicestudio/nord/pull/88/commits/be02cb278e38589dfd9cce0cbcc686d01ee050da.
If there is anything else I can do for you, feel free to hit me up :)

2018-01-17 04:57 UTC, arcticicestudio approved these changes
Looks fine now, thanks for the changes :+1:

2018-01-17 04:58 UTC, merged